name: Multiple tache
on: push
jobs:
  tache1_cowsay:
    runs-on: ubuntu-latest
    steps: 
      - name: telechargement code
        uses: actions/checkout@v4
      - name: installation de cowsay
        run: sudo apt-get install cowsay -y
      - name: executer cowsay
        run: cowsay -f dragon "bonjour DRAGON " > dragon.txt
      - name: executer cowsay
        run: grep -i "dragon" dragon.txt
      - name: lister les fichier
        run: ls -ltra
      - name: capture le fichier dragon.txt
        run: cat dragon.txt
  tache2_lister:
    runs-on: ubuntu-latest
    needs: tache1_cowsay
    steps: 
      - name: affichage
        run: ls      
        
   
