name: Multiple tache
on: push
jobs:
  build_cowsay:
    runs-on: ubuntu-latest
    steps: 
      - name: telechargement code
        uses: actions/checkout@v4
      - name: installation de cowsay
        run: sudo apt-get install cowsay -y
      - name: executer cowsay
        run: cowsay -f dragon "bonjour DRAGON " > dragon.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: dragon-artifact
          path: dragon.txt
        
  test_cowsay:
    runs-on: ubuntu-latest
    needs: build_cowsay
    steps: 
      - name: download artifact
        uses: actions/download-artifact@v5.0.0
        with: 
          name: dragon-artifact
      - name: existance du artificat
        run: ls
      - name: executer cowsay
        run: grep -i "dragon" dragon.txt
 
  run_cowsay:
    needs: test_cowsay
    runs-on: ubuntu-latest
    steps: 
      - name: download artifact
        uses: actions/download-artifact@v5.0.0
        with: 
          name: dragon-artifact
      - name: existance du artificat
        run: ls     
      - name: lancemend du fichier dragon.txt
        run: cat dragon.txt
        
   
