name: copier_code
on: push
jobs:
  test_copier_code:
    runs-on: ubuntu-latest
    steps: 
      - name: telechargement code
        uses: actions/checkout@v4
      - name: capturer readme
        run: cat README.md
   
